name: Get current repo state
on:
  push:
    branch: master

jobs:
  trace:
    name: example workflow
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Checkout cartographer_ros
        uses: actions/checkout@v2
      -
        name: last-commit
        id: last-commit
        uses: husarion-ci/action-get-repo-state@v0.2.0
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kamilmachon/test:arg_test
          file: Dockerfile
          build-args: LAST_COMMIT_INFO=${{ steps.last-commit.outputs.last-commit }}  
      -
        name: print
        run:  |
          echo "prev action output " ${{ steps.last-commit.outputs.last-commit }}  
