name: Publish Docker image
on:
  workflow_dispatch:
    inputs:
      target_branch_robo_cart:
        description: 'robo_cart branch that will be used in build'
        required: true
        default: 'master'
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - 
        name: Checkout repo
        uses: actions/checkout@v2
    -
      name: get info
      id: last-commit
      uses: ./.github/actions/custom_action
      with:
        repo-path: .
    -
      name: print
      run:  |
        echo "prev action output " ${{ steps.last-commit.outputs.last-commit }}  